# SwiftLint Configuration for Bridget
# Focus on safety and preventing common array bounds errors

disabled_rules:
  # Temporarily disable some rules that might be too strict for existing code
  - trailing_whitespace
  - line_length
  - function_body_length
  - type_body_length
  - file_length

opt_in_rules:
  # Safety-focused rules
  - array_init
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - discouraged_direct_init
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_imports
  - static_operator
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Custom rules for array safety
custom_rules:
  # Prevent manual array indexing that could cause bounds errors
  manual_array_indexing:
    name: "Manual Array Indexing"
    regex: 'for\s+i\s+in\s+.*\.\.<.*\.count.*\[i\s*[+\-]\s*[0-9]+\]'
    message: "Use safe iteration patterns like zip() or adjacentPairs instead of manual indexing"
    severity: warning
    
  # Prevent force unwrapping of array access
  force_array_access:
    name: "Force Array Access"
    regex: '\[.*\]!'
    message: "Use safe array access methods to prevent crashes"
    severity: warning
    
  # Encourage use of safe iteration patterns
  safe_iteration_patterns:
    name: "Safe Iteration Patterns"
    regex: 'zip\(.*,.*\.dropFirst\(\)\)'
    message: "Good! Using safe pairwise iteration"
    severity: error
    included: ".*Tests.*" # Only in test files for now

# File-specific rules
included:
  - Bridget/**/*.swift
  - BridgetTests/**/*.swift

excluded:
  - Bridget.xcodeproj
  - BridgetTests.xcresult
  - Documentation
  - Scripts
  - ml_export
  - Samples

# Line length configuration
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 500
  error: 1000

# Force unwrapping configuration
force_unwrapping:
  severity: error

# Implicitly unwrapped optional configuration
implicitly_unwrapped_optional:
  severity: error 